### ISSUE TITLE
How to apply muti-gpu?

### ISSUE THREAD

**Issue by DianJJ** [monniert/unicorn#5]
Hi, I try to retrain the code on muti-gpu by changing the cuda setting. But it still runs on a single gpu, can you help me with this? Thanks

**Comment by monniert** [comment]
Hi there sorry for the late reply! There is no official support for multi-gpu although I tried it at some point in the project. Basically there is a routine implemented that used to work, I have not tested it since a long time. Could you add `training.n_gpus = 2` in the config in addition to `cuda=0,1` when runing trainer.py?

**Comment by DianJJ** [comment]
Thanks for answering!  I have another question, I cannot find the 3d and mask iou evaluation for the PASCAL 3D dataset, how can I see these results?

**Comment by monniert** [comment]
Great question, you can find the original evaluation files here: https://github.com/shubham-goel/ucmr/tree/pascal/src/p3d_iou with [associated guidelines](https://github.com/shubham-goel/ucmr/blob/pascal/docs/training.md#other-categories). Since it is in MatLab I did not provide support in this repo

**Comment by DianJJ** [comment]
Hi, its me again, thanks for your patience. I retrain on the pascal 3D dataset,but the results do not look good.  The pose predictor tend to choose the same pose and the meshes exist irregular deformation. Is there any specific reason for this? Like random seeds? Other datasets looks pretty good though! Good work!

**Comment by monniert** [comment]
Hi Dianjj, yes can you try another seed and get back to me? Sometimes for real images (especially birds and cars), the learning got stuck into bad local minima as explained in the readme.md

**Comment by monniert** [comment]
Closing the issue since no further update, feel free to reopen if any!
