### ISSUE TITLE
3D-IoU Metric

### ISSUE THREAD

**Issue by sercanamac** [monniert/unicorn#6]
Dear Authors,

Could you please share how you evaluate the 3D-IoU metric? Thanks...

**Comment by monniert** [comment]
Hi @sercanamac, you can find the original evaluation files here: https://github.com/shubham-goel/ucmr/tree/pascal/src/p3d_iou with [associated guidelines](https://github.com/shubham-goel/ucmr/blob/pascal/docs/training.md#other-categories). Since it is in MatLab we do not provide support in this repo
